name: release
on:
    push:
        tags:
            - v*

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            -   uses: actions/checkout@v5
            -   name: get jvm_version
                id: jvm_version
                shell: pwsh
                run: gc ./gradle.properties|Select-String -Raw jvm_version= >> $env:GITHUB_OUTPUT
            -   uses: actions/setup-java@v5
                with:
                    distribution: microsoft
                    java-version: ${{ steps.jvm_version.outputs.jvm_version}}
            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v4
                with:
                    gradle-version: wrapper
                    cache-read-only: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/heads/mc/') }}
            -   name: build and release
                shell: pwsh
                run: ./gradlew githubRelease
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    TAG: ${{ github.ref }}
